[default_session]
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "tmux config"
path = "~/dotfiles/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "starship config"
path = "~/dotfiles/starship"
startup_command = "nvim starship.toml"

[[session]]
name = "nvim config"
path = "~/dotfiles/nvim"
