#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="fish kitty nvim scripts skhd tmux yabai zsh"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/dotfiles
fi

for folder in $(echo $STOW_FOLDERS)
do
  echo "stow $folder"
  stow -D $folder
  stow $folder
done

  
