require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.autocommands")
require("user.colorscheme")
-- require('user.tree')
require("user.telescope")
require("user.lualine")
-- require('user.bufferline')
require('user.lsp')
require("user.fidget")
require('user.cmp')
require('user.treesitter')
-- require("user.neoscroll")

vim.g.netrw_banner = 0
