#!/usr/bin/env sh
yabai -m config debug_output on

# Global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.50
yabai -m config window_border                off
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xff555555
yabai -m config normal_window_border_color   0xff06e5f9
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# Space settings
yabai -m config layout bsp
yabai -m config top_padding 15
yabai -m config bottom_padding 15
yabai -m config left_padding 15
yabai -m config right_padding 15
yabai -m config window_gap 15

# apps to ignore
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off
yabai -m rule --add app="^Cisco Webex Meetings$" manage=off

#Popus
yabai -m rule --add app="^DBeaver$" title="Connection.*configuration" manage=off
yabai -m rule --add app="^IntelliJ IDEA$"

yabai -m space 1 --label term
yabai -m space 2 --label ide
yabai -m space 3 --label web
yabai -m space 4 --label slack
yabai -m space 5 --label work
yabai -m space 6 --label other

yabai -m rule --add app="^iTerm2$" space=term
yabai -m rule --add app="^IntelliJ IDEA$" space=ide
yabai -m rule --add app="^Chrome$" space=web
yabai -m rule --add app="^Firefox$" space=web
yabai -m rule --add app="^Slack$" space=slack
yabai -m rule --add app="^Outlook$" space=work
yabai -m rule --add app="^DBeaver$" space=work
yabai -m rule --add app="^Notion$" space=other
