#!/usr/bin/env bash
 if [[ $# -eq 1 ]]; then
     selected=$1
 else
     directories=$(find ~/Documents/shopz ~/Documents/personal ~/Documents/danube ~/Documents/lmfs -mindepth 1 -maxdepth 1 -type d)
     directories=$(echo -e "~/Documents/shopz\n~/Documents/personal\n~/Documents/danube\n~/Documents/lmfs"; echo "$directories")
     selected=$(echo "$directories" | fzf-tmux -p 55%,60%  --layout=reverse \
       --prompt="Select project to connect to: " \
   --border --no-info --border-label="Projects")
 fi

 if [[ -z $selected ]]; then
     exit 0
 fi

 selected_name=$(basename "$selected" | tr . _)
 tmux_running=$(pgrep tmux)

 if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
     tmux new-session -s $selected_name -c $selected
     exit 0
 fi

 if ! tmux has-session -t=$selected_name 2> /dev/null; then
     tmux new-session -ds $selected_name -c $selected
 fi

tmux switch-client -t $selected_name
